### ISSUE TITLE
Train自己音库的vocoder

### ISSUE THREAD

**Issue by SoloPro-Git** [openvpi/vocoders#1]
你好,请问如果想训练自己的声码器该怎么操作呢.

我这边遇到了一个问题是 我自己声库跑出来的模型和社区提供的vocoder不匹配导致了有杂音.

在开发tts的时候也遇到了这个问题,解决办法是针对自己的声库train vocoder. 

所以想请教下哪里可以训练svc对应能用的vocoder呢

**Comment by yqzhishen** [comment]
很抱歉此前都忘了回复。首先请你确定问题是否确实由声码器而不是自己的训练数据引起，其次请你确定是不是mel参数不匹配导致的；声码器是使用很多样的数据训练出来的，一般在unseen speaker上的劣化没有你说的那么严重。

**Comment by quickvc** [comment]
@yqzhishen 您好，我想在您的声码器的基础上fine tune，请问您在训练过程中，将wav转为频谱的代码是什么样的呢？

**Comment by yqzhishen** [comment]
> @yqzhishen 您好，我想在您的声码器的基础上fine tune，请问您在训练过程中，将wav转为频谱的代码是什么样的呢？

https://github.com/openvpi/DiffSinger/blob/refactor/modules/nsf_hifigan/nvSTFT.py
