### ISSUE TITLE
Finetuning

### ISSUE THREAD

**Issue by Likkkez** [openvpi/vocoders#2]
Hi! I'd like to finetune the nsf-hifigan checkpoint. Where can I get the code for finetuning/training? Can't find it anywhere.

**Comment by yqzhishen** [comment]
We did not upload the actual training code to GitHub, but will these repos be helpful to you?
https://github.com/Liujingxiu23/NSF-HIFIGAN
https://github.com/fishaudio/fish-diffusion

**Comment by Likkkez** [comment]
> We did not upload the actual training code to GitHub, but will these repos be helpful to you? https://github.com/Liujingxiu23/NSF-HIFIGAN https://github.com/fishaudio/fish-diffusion

Ah, thank you I'll take a look!
